#!/bin/sh

# 添加到ucitrack配置
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@virtualgw[-1]
	add ucitrack virtualgw
	set ucitrack.@virtualgw[-1].init=virtualgw
	commit ucitrack
EOF

# 确保翻译文件可用
if [ -d /usr/lib/lua/luci/i18n ]; then
    if [ -f /usr/lib/lua/luci/i18n/virtualgw.zh-cn.lmo ]; then
        rm -f /usr/lib/lua/luci/i18n/virtualgw.zh-cn.lmo
    fi
    if [ -f /usr/lib/lua/luci/i18n/virtualgw.zh_Hans.lmo ]; then
        rm -f /usr/lib/lua/luci/i18n/virtualgw.zh_Hans.lmo
    fi
    
    # 复制翻译文件
    cp -f /usr/share/luci/i18n/virtualgw.zh-cn.* /usr/lib/lua/luci/i18n/ 2>/dev/null
    cp -f /usr/share/luci/i18n/virtualgw.zh_Hans.* /usr/lib/lua/luci/i18n/ 2>/dev/null
fi

# 确保LuCI缓存被清除
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0 